# insecure! 
# do not use this kind of pass management in production
apiVersion: v1
kind: ConfigMap
metadata:
  name: backoffice-proxy-configs
data:
  UPSTREAM: http://backoffice-svc:8080
  PORT: "8080"
  PUBLIC_KEY: |
    -----BEGIN PUBLIC KEY-----
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqyTOr6RUZ16FsR4KgBDX
    47obxpeGaSHdX5y9iMs0cajkZoklkKbLElTfSE3Qtx6T1hBCu6Qd4Mm3qvnxvHxs
    somEzvnJza+stTRJIf1mhuZVrzyQ/T2K6RfH+EQeNWUPMZse7ea7e7Vkm2h/jAIk
    M4/3/5VbyHXaXot26ncf3H3eQ1ehl5oXTZwMVz6rLwBCad5GXTvvjOC4AXcjiACw
    FZXUuNDxAFtVxcUnalAGKOSZmYUjtOZiN8FENdap3rdv8NVJ/FzZxnRjm2qwFJH9
    e/dlo3fVf8EDcimjqkgKKrn1Dj+Z/8xyYfIr/Xtf1sbVWETDtz4S2HAmIYduslSc
    mwIDAQAB
    -----END PUBLIC KEY-----



